name: Build Tool

on:
  create:
      branches:
        - release/**
        
  push:
      branches:
        - main
        - development 
      paths-ignore:
        - 'docs/**'
        - 'README.md'
        - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.os }} - ${{ matrix.arch }}
    strategy:
      matrix:
        os: [linux, windows, darwin, freebsd]
        arch: [amd64, 386]
        include:
          - os: linux
            goos: linux
            goarch: amd64
          - os: linux
            goos: linux
            goarch: 386
          - os: windows
            goos: windows
            goarch: amd64
            binary_ext: ".exe"
          - os: windows
            goos: windows
            goarch: 386
            binary_ext: ".exe"
          - os: darwin
            goos: darwin
            goarch: amd64
          - os: freebsd
            goos: freebsd
            goarch: amd64
          - os: freebsd
            goos: freebsd
            goarch: 386
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      VERSION: "latest"
      OUTPUT_DIR: ".bin"
      BINARY_NAME: "nioscli${{ matrix.binary_ext }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get Build Version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          tag_version="${GITHUB_REF#refs/tags/}"
          echo "Detected Version from Tag: $tag_version"
          echo "VERSION=$tag_version" >> $GITHUB_ENV
        shell: pwsh
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build binary
        run: make build VERSION=${{ env.VERSION }}

      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: "nioscli-${{ matrix.goos }}-${{ matrix.goarch }}"
          path: ".bin/${{ matrix.goarch }}/${{ matrix.goos }}/"
      - name: Create GitHub Release
        if: github.ref_type == 'tag'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload Build Binaries to Release
        if: github.ref_type == 'tag'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .bin/${{ matrix.goarch }}/${{ matrix.goos }}/$BINARY_NAME
          asset_name: "nioscli-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.binary_ext }}"
          asset_content_type: application/octet-stream
